default: &default
  pivotal_tracker_project_id: project_id
  pivotal_tracker_token: token
  action_mailer_from: baker@cupcake.world
  rollbar_access_token: rollbar_access_token

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default
